title: "R-Ladies Global"
theme: "hugo-rladies"
publishDir: "public"

languageCode: "en"
defaultContentLanguage: "en"
summaryLength: 30

pygmentsUseClasses: true
enableRobotsTXT: true
enableGitInfo: true
minify:
  minifyOutput: true

buildFuture: true
buildDrafts: true

ignoreLogs:
  - "warning-goldmark-raw-html"

ignoreFiles:
  - "\\.Rmd$"
  - "\\.qmd$"
  - "_cache$"
  - "\\.DS_Store"
  - "_files$"
  - "content/*/\\*/index\\*\\.html"
  - "_cache$"
  - "README"
  - "README_img/"

# Add this to config/_default/config.yaml

outputFormats:
  Calendar:
    mediaType: text/calendar
    baseName: calendar
    isPlainText: true
    protocol: webcal://

outputs:
  home:
    - HTML
  section:
    - HTML
  page:
    - HTML
    - RSS
