title: "R-Ladies Global"
theme: "hugo-rladies"
publishDir: "public"

languageCode: "en"
defaultContentLanguage: "en"
summaryLength: 30

pygmentsUseClasses: true
enableRobotsTXT: true
enableGitInfo: true
minify:
  minifyOutput: true

buildFuture: true
buildDrafts: true
  
ignoreFiles:
  - "\\.Rmd$"
  - "\\.qmd$"
  - "_cache$"
  - "\\.DS_Store"
  - "_files$"
  - "content/*/\\*/index\\*\\.html"
  - "_cache$"
  - "README"
  - "README_img/"
#[outputs]
#  home = ["HTML", "RSS", "JSON"]

ignoreLogs:
  - warning-goldmark-raw-html
