main:
  - identifier: events
    url: /activities/events/
    weight: 1

  - identifier: chapters
    url: /chapters/
    weight: 2

  - identifier: directory
    url: /directory/
    weight: 3

  - identifier: blog
    url: /blog
    weight: 4

  - identifier: activities
    weight: 5
  - identifier: mentoring
    url: /activities/mentoring/
    weight: 3
    parent: activities
  - identifier: coordinated
    url: /activities/gt-coordinated/
    weight: 4
    parent: activities
  - identifier: rladies-blogs
    url: /activities/rladies-blogs
    weight: 5
    parent: activities
  - identifier: press
    url: /press
    weight: 6
    parent: activities
  - identifier: about-us
    url: "#"
    weight: 99
  - identifier: mission
    url: /about-us/mission/
    weight: 1
    parent: about-us
  - identifier: get-involved
    url: /about-us/involved/
    weight: 2
    parent: about-us
  - identifier: global-team
    url: /about-us/global-team/
    weight: 3
    parent: about-us
  - identifier: history
    url: /about-us/history/
    weight: 4
    parent: about-us
  - identifier: news
    url: /news/
    weight: 5
    parent: about-us
  - identifier: coc
    url: /coc/
    weight: 6
    parent: about-us
