name: R-Ladies Global
email: 'info[at]rladies[dot]org'
avatar: images/logo.png
avatarclass: rounded
year: 2013

banner: images/user2017.jpg
bannerOverlay: '#88398a'

favicon: images/favicon.png
DateForm: 2 January 2006
showSubheader: false

footerEnableContact: true
footerEnableFollowme: true
footerEnableTextWidget: true
footerEnableLangWidget: true

social:
  - title: bluesky
    handle: ''
    relme: true
    footer: true
    sharethis: true
    network: ''
  - title: mastodon
    handle: '@RLadiesGlobal@hachyderm.io'
    relme: true
    footer: true
    sharethis: true
    network: ''
  - title: twitter
    handle: 'RLadiesGlobal'
    footer: false
    sharethis: false
    network: twitter
  - title: instagram
    handle: 'rladiesglobal'
    footer: true
    sharethis: false
    network: ''
  - title: github
    handle: 'rladies'
    footer: true
    sharethis: false
    network: ''
  - title: meetup
    handle: 'pro/rladies/'
    footer: true
    sharethis: true
    network: ''
  - title: youtube
    handle: 'channel/UCDgj5-mFohWZ5irWSFMFcng'
    footer: true
    sharethis: true
    network: ''
twitter:
  - title: We are R-Ladies
    handle: 'WeAreRLadies'
    footer: true
    sharethis: false
    network: ''
  - title: IWD R-Ladies
    handle: 'rladies_iwd'
    footer: true
    sharethis: false
    network: ''
