[[main]]
    name = "Inicio"
    identifier = "home"
    url = "/"
    weight = 1
    
[[main]]
    name = "Sobre nosotros"
    url = "#"
    identifier = "about-us"
    weight = 2
[[main]]
    name = "Misión"
    url = "/about-us/mission/"
    weight = 1
    parent = "about-us"
[[main]]
    name = "Involúcrate"
    url = "/about-us/involved/"
    weight = 2
    parent = "about-us"
[[main]]
    name = "Conoce al equipo"
    url = "/about-us/global-team/"
    weight = 3
    parent = "about-us"
[[main]]
    name = "Historia"
    url = "/about-us/history/"
    weight = 4
    parent = "about-us"

    
[[main]]
    name = "Directorio"
    url = "/directory/"
    weight = 3
    
[[main]]
    name = "Actividades"
    identifier = "activities"
    url = "#"
    weight = 4
[[main]]
    name = "Eventos"
    url = "/activities/events/"
    weight = 1
    parent = "activities"
[[main]]
    name = "Programa de mentores"
    url = "/activities/mentoring/"
    weight = 3
    parent = "activities"
[[main]]
    name = "Coordinado por el equipo"
    url = "/activities/gt-coordinated/"
    weight = 4
    parent = "activities"
[[main]]
    name = "Panel de Control Global"
    url = "https://benubah.github.io/r-community-explorer/rladies.html"
    weight = 5
    parent = "activities"
[[main]]
    name = "Blogs de R-Ladies"
    url = "activities/rladies-blogs"
    weight = 6
    parent = "activities"
    
[[main]]
    name = "Blog"
    url = "/post"
    weight = 5
    
