baseURL = "http://blog.rladies.org/"
languageCode = "en-us"
title = "R-Ladies"
theme = "minimal"
relativeURLs = true
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "R-Ladies Global"
    profilePic = "https://raw.githubusercontent.com/rladies/starter-kit/master/logo/R-LadiesGlobal_RBG_online_LogoWithText.png"
    horizontalPic = "https://raw.githubusercontent.com/rladies/starter-kit/master/logo/R-LadiesGlobal_RBG_online_LogoWithText_Horizontal.png"
    description = "R-Ladies Global Blog"
    githubUsername = "rladies"
    accent = "#88398A"
    showBorder = true
    backgroundColor = "white"
    font = "Open Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["r", "python", "bash"]

[[menu.main]]
    url = "https://rladies.org/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:info@rladies.org"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rladies/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/RLadiesGlobal/"
    name = "twitter"
    weight = 3
    
[[menu.icon]]
    url = "https://www.meetup.com/es-ES/topics/r-ladies/all/"
    name = "meetup"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/company/17981653/"
    name = "linkedin"
    weight = 5
