baseURL = "http://blog.rladies.org/"
languageCode = "en-us"
title = "R-Ladies Blog"
theme = "janeadapt"
relativeURLs = true
publishDir = "public"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

copyright = "R-Ladies CC-BY"
pygmentsUseClasses = true
enableEmoji = true

# Getting raw html to render 
[markup] 
  defaultMarkdownHandler = "blackfriday"
  
[params]
    author = "R-Ladies Global"
    since = 2012
    profilePic = "https://raw.githubusercontent.com/rladies/starter-kit/master/logo/R-LadiesGlobal_RBG_online_LogoWithText.png"
    horizontalPic = "https://raw.githubusercontent.com/rladies/starter-kit/master/logo/R-LadiesGlobal_RBG_online_LogoWithText_Horizontal.png"
    description = "R-Ladies Global Blog"
    githubUsername = "rladies"
    accent = "#88398A"
    showBorder = true
    backgroundColor = "white"
    font = "Open Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["r", "python", "bash"]
    showMenuLanguageChooser = true

  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  # 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
  [params.gitInfo]
    gitRepo = "https://github.com/rladies/blog"
    showCommitMessage = false

customCSS = ["css/syntax_lovelace.css"] 

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
    url = "https://rladies.org/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2
    
defaultContentLanguage = "en"  # Default language to use (if you setup multilingual support)
[Languages.en]
  languageCode = "en"
  languageName = "English"
  
[Languages.fr] 
  languageCode = "fr"
  languageName = "Français"


[Languages.pt]
  languageCode = "pt"
  languageName = "Português"

[Languages.es]
  languageCode = "es"
  languageName = "Español"
  
  
   [params.social]                                         # 社交链接
    a-email = "mailto:info@rladies.org"
    c-twitter = "https://twitter.com/RLadiesGlobal"
    e-linkedin = "https://www.linkedin.com/company/17981653/"
    g-github = "https://github.com/rladies"
    m-instagram = "https://www.instagram.com/rladiesglobal"
    t-youtube = "https://www.youtube.com/channel/UCDgj5-mFohWZ5irWSFMFcng"

